sudo: true

language: python

services:
  - docker

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install tox tox-travis codecov

before_script:
  - docker run -d --name travis-virtuoso -p 8890:8890 -e SPARQL_UPDATE=true tenforce/virtuoso:1.2.0-virtuoso7.2.2
  - docker run -d -p 3030:3030 --name travis-fuseki -e ADMIN_PASSWORD=PASSWORD -e ENABLE_DATA_WRITE=true -e ENABLE_UPDATE=true -e ENABLE_UPLOAD=true secoresearch/fuseki

script:
  - tox

after_script:
  - docker rm -vf travis-virtuoso
  - docker rm -vf travis-fuseki

after_success:
  - codecov

jobs:
  include:
    - stage: deploy
      python: 3.6
      deploy:
        provider: pypi
        user: __token__
        password:
          secure: "tqSHaed2aAaJnEvCXLz6BelDbVCyJhdlY/2XZX+S0cD/X24t31EGPaA8WTypU3VmQMzKLK9NZfM7qw7Ua42M3eL2EHXHnRKPZQifPdxDX4ZUIMrcFtmyTRN95CboxQrE6ffPGyx9RAvI4ekmE2H744rgyMx2wjcn9y3g5j7f/OpuGyhk+skqXIskPQj3ixfiZN2LSFxwHOAUf9u+vb+sFUwOd0MYZoXvhUwwD/JJOrjyHSXTwKRZZnGTdWMaBdbS6dejsCEZ+Qqf3LdASYQHSc4awb7qayl+1lO+AKpj80BT4deHNf7gWLIV3jq9WYHOBQzfbIEse+Ca5b6NfgyrRC0G2xD6HfyRpFMLScm7xmilbWl08Tr+4fMH1sqtk/81HfC+6ESLs4s66u/yb7DHGz2SDh0TJxZV8DvlbdbQM2m1DolwTIMgr3ZJSgO6ukwhJH4LhTFqhX0XH/URYjZZpVV0soJ38F8nkYZoYWmrsOK81dec7Ld7mRJXeF17e1hmg1cFt7Nh1DWt0kKEfP4IRNRoyUwg6PI6/suPfm0XkyfUMvUlnvP9wmrLqmucT2oDc9mpB5Tt4FNmScnkb54LbOHEFtTgYGoNiqzsrNwJLJ9hZ8uURcDljddwWnd4jotV+/XrC0oLgEYhRYpy/m2S4jjDqosXsSuvdL5v1cnT0mo="
        distributions: "sdist bdist_wheel"
        on:
          tags: true
          all_branches: true
      script: true
      after_success: true  # do nothing
